# Generated by Django 2.2.16 on 2021-10-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_remove_title_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
