# Generated by Django 2.2.16 on 2021-10-14 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20211014_1750'),
        ('categories', '0006_title_rating'),
    ]

    operations = [
    ]
